Results_Aggregator/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('competition/', include('competition.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^.*$', RedirectView.as_view(url='/'), name='homepage-redirect'),
]

competition/urls.py
from django.views.generic import RedirectView
from django.urls import path, include, re_path
from competition.views import *

app_name = 'competition'

urlpatterns = [
    # /competition
    path('', IndexView.as_view(), name='competition-index'),
    path('<int:competition_pk>/', DetailsView.as_view(), name='competition-details'),
    path('add/', CompetitionCreate.as_view(), name='competition-add'),
    path('<int:competition_pk>/delete/', CompetitionDelete.as_view(), name='competition-delete'),
    path('<int:competition_pk>/update/', CompetitionUpdate.as_view(), name='competition-update'),
    path('<int:competition_pk>/change_archive/', change_competition_archive_status, name='competition-change-archive-status'),
    path('<int:competition_pk>/start_competition/', start_competition, name='competition-start'),
    path('<int:competition_pk>/restart_competition/', restart_competition, name='competition-restart'),
    path('<int:competition_pk>/stop_competition/', stop_competition, name='competition-stop'),
    path('<int:competition_pk>/join_competition/', join_competition, name='competition-join'),
    path('<int:competition_pk>/remove_student/', remove_student_from_competition, name='competition-remove-student'),
    path('<int:competition_pk>/competition_result/', GenerateResultTable.as_view(), name='competition-generate-result'),
    path('<int:competition_pk>/competition_result_ajax/', generate_result_table_ajax, name='competition-generate-result-ajax'),
    path('<int:competition_pk>/question/', include('question.urls')),
    re_path(r'^.*$', RedirectView.as_view(url='/')),
]

question/urls.py
from django.views.generic import RedirectView
from django.urls import path, include, re_path
from question.views import *

app_name = 'question'

urlpatterns = [
    # /competition/<competition_pk>/question/
    path('<int:question_pk>/', DetailsView.as_view(), name='question-details'),
    path('add/', QuestionCreate.as_view(), name='question-add'),
    path('<int:question_pk>/delete/', QuestionDelete.as_view(), name='question-delete'),
    path('<int:question_pk>/update/', QuestionUpdate.as_view(), name='question-update'),
    path('<int:question_pk>/question_file/add/', QuestionFileCreate.as_view(), name='question-file-add'),
    path('<int:question_pk>/question_file/<int:question_file_pk>/delete/', QuestionFileDelete.as_view(), name='question-file-delete'),
    path('<int:question_pk>/question_file/<int:question_file_pk>/update/', QuestionFileUpdate.as_view(), name='question-file-update'),
    path('<int:question_pk>/student_answer/', include('student_answer.urls')),
    re_path(r'^.*$', RedirectView.as_view(url='/')),
]

user/urls.py
from django.urls import include, path
from .views import *

app_name = 'user'

urlpatterns = [
    # user/
    path('lecturer/', include('django.contrib.auth.urls')),
    path('lecturer/list/', LecturerList.as_view(), name='lecturer-list'),
    path('lecturer/register/', LecturerRegister.as_view(), name='lecturer-register'),
    path('lecturer/<int:lecturer_pk>/delete/', lecturer_delete, name='lecturer-delete'),
    path('student/', include('django.contrib.auth.urls')),
    path('student/register/', StudentRegister.as_view(), name='student-register'),
]

question/models.py
from django.db import models
from django.urls import reverse
from competition.models import Competition
import os


# determine the upload_directory for uploaded question file (including answer) in MEDIA_ROOT
def upload_directory(instance, filename):
    path = os.path.join(str(instance.question.competition.id), str(instance.question.id))
    path = os.path.join(path, filename)
    return path


class Question(models.Model):
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('question:question-details', kwargs={'question_pk': self.pk})

    def __str__(self):
        return '{} {} {}'.format(str(self.pk), self.name, self.creation_date)


class QuestionFile(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    question_file = models.FileField(upload_to=upload_directory)
    answer_file = models.FileField(upload_to=upload_directory)

    def get_question_file_text(self):
        file = open(self.question_file.path, 'r')
        return file.read()

    def get_answer_file_text(self):
        file = open(self.answer_file.path, 'r')
        return file.read()

    def __str__(self):
        return '{} || {}'.format(self.question_file.name, self.answer_file.name)

student_answer/models.py
from django.db import models
from django.contrib.auth.models import User
from competition.models import Competition
from question.models import Question
from user.models import Student
import os


# determine the upload_directory for uploaded student_answer file (including answer) in MEDIA_ROOT
def upload_directory(instance, filename):
    path = os.path.join(str(instance.question.competition.id), str(instance.question.id))
    path = os.path.join(path, filename)
    return path


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    submission_time = models.DateTimeField(auto_now_add=True)
    answer_file = models.FileField(upload_to=upload_directory)
    correct_count = models.IntegerField(null=True)
    solved = models.BooleanField(default=False)

    def get_answer_file_text(self):
        file = open(self.answer_file.path, 'r')
        return file.read()

    def __str__(self):
        return '{} {} {} {}'.format(str(self.pk), self.student.user.username, self.answer_file.path, self.submission_time)


class StudentAnswerResult(models.Model):
    student_answer = models.ForeignKey(StudentAnswer, on_delete=models.CASCADE)
    result_file = models.FileField(upload_to=upload_directory)
    is_correct = models.BooleanField(default=False)

    def get_result_file_text(self):
        file = open(self.result_file.path, 'r')
        return file.read()

    def __str__(self):
        return '{} {}'.format(self.result_file.path, str(self.is_correct))

question/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from competition.models import Competition
from .models import Question, QuestionFile
from user.models import Student
from student_answer.models import StudentAnswer
from django.urls import reverse
from helper_functions.file_management import trim_text_file


# list question_files and submitted answer_files
class DetailsView(DetailView):
    model = Question
    template_name = 'question/details.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        context = super(DetailsView, self).get_context_data(**kwargs)
        # if question solved, remove 'Add Question' button and add red Solved header
        if self.request.user.groups.filter(name='Student').exists():
            student = Student.objects.get(user=self.request.user)
            context['solved'] = False
            student_answer = StudentAnswer.objects.filter(student=student, question=self.kwargs['question_pk'])
            context['student_answer_list'] = student_answer
            if student_answer.filter(solved=True).count() > 0:
                context['solved'] = True
        elif self.request.user.groups.filter(name='Lecturer').exists():
            context['student_answer_list'] = StudentAnswer.objects.filter(
                question=self.kwargs['question_pk'],
                student__user__is_active=True,
            )
        return context


class QuestionCreate(CreateView):
    model = Question
    fields = ['name', 'description']
    template_name = 'question/question_form.html'

    def form_valid(self, form):
        competition_pk = self.kwargs.get('competition_pk')
        form.instance.competition = Competition.objects.get(pk=competition_pk)
        form.save()
        return super(QuestionCreate, self).form_valid(form)

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        question_pk = self.object.id
        return reverse('competition:question:question-details', kwargs={
            'competition_pk': competition_pk,
            'question_pk': question_pk
        })


class QuestionUpdate(UpdateView):
    model = Question
    pk_url_kwarg = 'question_pk'
    fields = ['name', 'description']
    template_name = 'question/question_form.html'

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        return reverse('competition:competition-details', kwargs={'competition_pk': competition_pk})


class QuestionDelete(DeleteView):
    model = Question
    pk_url_kwarg = 'question_pk'

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        return reverse('competition:competition-details', kwargs={'competition_pk': competition_pk})


class QuestionFileCreate(CreateView):
    model = QuestionFile
    pk_url_kwarg = 'question_pk'
    fields = ['question_file', 'answer_file']
    template_name = 'question/question_file_form.html'

    def form_valid(self, form):
        question_pk = self.kwargs.get('question_pk')
        form.instance.question = Question.objects.get(pk=question_pk)
        form.save()
        question_file = QuestionFile.objects.get(pk=form.instance.id)
        trim_text_file(question_file.question_file.path)
        trim_text_file(question_file.answer_file.path)
        return super(QuestionFileCreate, self).form_valid(form)

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        question_pk = self.kwargs.get('question_pk')
        return reverse('competition:question:question-details', kwargs={
            'competition_pk': competition_pk,
            'question_pk': question_pk,
        })


class QuestionFileUpdate(UpdateView):
    model = QuestionFile
    fields = ['question_file', 'answer_file']
    template_name = 'question/question_file_form.html'
    pk_url_kwarg = 'question_file_pk'

    def form_valid(self, form):
        form.save()
        question_file = QuestionFile.objects.get(pk=form.instance.id)
        trim_text_file(question_file.question_file.path)
        trim_text_file(question_file.answer_file.path)
        return super(QuestionFileUpdate, self).form_valid(form)

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        question_pk = self.kwargs.get('question_pk')
        return reverse('competition:question:question-details', kwargs={
            'competition_pk': competition_pk,
            'question_pk': question_pk,
        })


class QuestionFileDelete(DeleteView):
    model = QuestionFile
    pk_url_kwarg = 'question_file_pk'

    def get_success_url(self):
        competition_pk = self.kwargs.get('competition_pk')
        question_pk = self.kwargs.get('question_pk')
        return reverse('competition:question:question-details', kwargs={
            'competition_pk': competition_pk,
            'question_pk': question_pk,
        })

templates/question/details.html
{% extends 'generic/base.html' %}
{% load auth_extras %}
{% comment %} template to display list of question files and uploaded student_answer {% endcomment %}
{% block title %} Question Details {% endblock %}

{% block question_home %} <a href="{% url 'competition:competition-details' question.competition.id %}">Question List</a><br> {% endblock %}

{% block body %}
    {% comment %} inform student if they've solved the problem {% endcomment %}
    {% if user.is_authenticated %}
        {% if user|has_group:"Student" %}
            {% if solved == True and question.competition.is_active == True %}
            <h1 style="color: red">Solved!</h1>
            {% endif %}
        {% endif %}
    {% endif %}
    {% comment %} general details on the question {% endcomment %}
    <h1>{{ question.name }}</h1>
    <h3>{{ question.description }}</h3>
    <h4>{{ question.creation_date|date:"j/n/Y h:i A" }}</h4>

    {% comment %} lecturer can add / update / delete question files {% endcomment %}
    {% if user.is_authenticated %}
        {% if user|has_group:"Lecturer" %}
        <h3>Questions:</h3>
        {% if question.competition.is_active == False %}
        <form action="{% url 'competition:question:question-file-add' question.competition.id question.id %}" method="get" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{ question.id }}"/>
            <label>Add Question File: </label>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </form>
        {% endif %}

        <ol>
            {% for question_file in question.questionfile_set.all %}
                <li>
                    <label>{{ question_file }}</label>
                    {% if user.is_authenticated %}
                        {% if user|has_group:"Lecturer" %}
                            {% if question.competition.is_active == False %}
                            <form action="{% url 'competition:question:question-file-update' question.competition.id question.id question_file.pk %}" method="get" style="display: inline;">
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>
                            </form>
                            <form action="{% url 'competition:question:question-file-delete' question.competition.id question.id question_file.pk %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="question_id" value="{{ question.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            {% endif %}
                        {% endif %}
                        {% comment %} display question and answer file in textarea {% endcomment %}
                        <br>
                        <label><textarea rows="15" cols="50">{{ question_file.get_question_file_text }}</textarea>
                        {% if user|has_group:"Lecturer" %}
                        <textarea rows="15" cols="50">{{ question_file.get_answer_file_text }}</textarea></label>
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
        {% endif %}
    {% endif %}

    {% comment %} student can only submit if they haven't solve the question {% endcomment %}
    <h3>Submitted Answers:</h3>
    {% if user.is_authenticated %}
        {% if user|has_group:"Student" %}
            {% if solved == False and question.competition.is_active == True %}
            <form action="{% url 'competition:question:student_answer:student-answer-add' question.competition.id question.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="question_id" value="{{ question.id }}"/>
                <label>Add Answer File: </label>
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </form>
            {% endif %}
        {% endif %}
    {% endif %}

    {% comment %} display result of submitted student_answer {% endcomment %}
    <ol>
        {% for student_answer in student_answer_list reversed %}
            <li><label>{{ student_answer }}</label><br>
                <label>Num of Correct: {{ student_answer.correct_count }} / {{ question.questionfile_set.count }}</label><br>
                {% for result_file in student_answer.studentanswerresult_set.all %}
                    <br><label>{{ result_file.id }}, {{ result_file.is_correct }}</label><br>
                    <label><textarea rows="15" cols="50">{{ result_file.get_result_file_text }}</textarea></label>
                {% endfor %}
            </li>
        {% endfor %}
    </ol>
{% endblock %}

templates/question/question_file_form.html
<form action="" method="post" enctype="multipart/form-data" role="form">
    {% csrf_token %}
    <legend>Add Question File</legend>

    {% include 'generic/form-template.html' %}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/question/question_form.html
<form action="" method="post" enctype="multipart/form-data" role="form">
    {% csrf_token %}
    <legend>Add Question</legend>

    {% include 'generic/form-template.html' %}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>