Results_Aggregator/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('competition/', include('competition.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^.*$', RedirectView.as_view(url='/'), name='homepage-redirect'),
]

competition/urls.py
from django.views.generic import RedirectView
from django.urls import path, include, re_path
from competition.views import *

app_name = 'competition'

urlpatterns = [
    # /competition
    path('', IndexView.as_view(), name='competition-index'),
    path('<int:competition_pk>/', DetailsView.as_view(), name='competition-details'),
    path('add/', CompetitionCreate.as_view(), name='competition-add'),
    path('<int:competition_pk>/delete/', CompetitionDelete.as_view(), name='competition-delete'),
    path('<int:competition_pk>/update/', CompetitionUpdate.as_view(), name='competition-update'),
    path('<int:competition_pk>/change_archive/', change_competition_archive_status, name='competition-change-archive-status'),
    path('<int:competition_pk>/start_competition/', start_competition, name='competition-start'),
    path('<int:competition_pk>/restart_competition/', restart_competition, name='competition-restart'),
    path('<int:competition_pk>/stop_competition/', stop_competition, name='competition-stop'),
    path('<int:competition_pk>/join_competition/', join_competition, name='competition-join'),
    path('<int:competition_pk>/remove_student/', remove_student_from_competition, name='competition-remove-student'),
    path('<int:competition_pk>/competition_result/', GenerateResultTable.as_view(), name='competition-generate-result'),
    path('<int:competition_pk>/competition_result_ajax/', generate_result_table_ajax, name='competition-generate-result-ajax'),
    path('<int:competition_pk>/question/', include('question.urls')),
    re_path(r'^.*$', RedirectView.as_view(url='/')),
]

user/urls.py
from django.urls import include, path
from .views import *

app_name = 'user'

urlpatterns = [
    # user/
    path('lecturer/', include('django.contrib.auth.urls')),
    path('lecturer/list/', LecturerList.as_view(), name='lecturer-list'),
    path('lecturer/register/', LecturerRegister.as_view(), name='lecturer-register'),
    path('lecturer/<int:lecturer_pk>/delete/', lecturer_delete, name='lecturer-delete'),
    path('student/', include('django.contrib.auth.urls')),
    path('student/register/', StudentRegister.as_view(), name='student-register'),
]

templates/generic/base.html
{% comment %} template to show the generic navbar in all page {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Quiz{% endblock %}</title>
    {% load staticfiles %}
    {% load auth_extras %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

    {% block additional_header %} {% endblock %}
</head>

<body>
{% if user.is_authenticated %}
    Hi, {{ user.username }}!
    <a href="{% url 'user:logout' %}">logout</a><br>
    {% if user|has_group:"Lecturer" or user.is_superuser %}
    <a href="{% url 'user:lecturer-list' %}">Lecturer List</a><br>
    {% endif %}
    <a href="{% url 'competition:competition-index' %}">Home</a><br>
    {% block question_home %} {% endblock %}
{% endif %}

{% block body %}
{% endblock %}
</body>

templates/generic/form-template.html
{% comment %} generic template to format django form {% endcomment %}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}