Results_Aggregator/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('competition/', include('competition.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^.*$', RedirectView.as_view(url='/'), name='homepage-redirect'),
]

competition/urls.py
from django.views.generic import RedirectView
from django.urls import path, include, re_path
from competition.views import *

app_name = 'competition'

urlpatterns = [
    # /competition
    path('', IndexView.as_view(), name='competition-index'),
    path('<int:competition_pk>/', DetailsView.as_view(), name='competition-details'),
    path('add/', CompetitionCreate.as_view(), name='competition-add'),
    path('<int:competition_pk>/delete/', CompetitionDelete.as_view(), name='competition-delete'),
    path('<int:competition_pk>/update/', CompetitionUpdate.as_view(), name='competition-update'),
    path('<int:competition_pk>/change_archive/', change_competition_archive_status, name='competition-change-archive-status'),
    path('<int:competition_pk>/start_competition/', start_competition, name='competition-start'),
    path('<int:competition_pk>/restart_competition/', restart_competition, name='competition-restart'),
    path('<int:competition_pk>/stop_competition/', stop_competition, name='competition-stop'),
    path('<int:competition_pk>/join_competition/', join_competition, name='competition-join'),
    path('<int:competition_pk>/remove_student/', remove_student_from_competition, name='competition-remove-student'),
    path('<int:competition_pk>/competition_result/', GenerateResultTable.as_view(), name='competition-generate-result'),
    path('<int:competition_pk>/competition_result_ajax/', generate_result_table_ajax, name='competition-generate-result-ajax'),
    path('<int:competition_pk>/question/', include('question.urls')),
    re_path(r'^.*$', RedirectView.as_view(url='/')),
]

user/urls.py
from django.urls import include, path
from .views import *

app_name = 'user'

urlpatterns = [
    # user/
    path('lecturer/', include('django.contrib.auth.urls')),
    path('lecturer/list/', LecturerList.as_view(), name='lecturer-list'),
    path('lecturer/register/', LecturerRegister.as_view(), name='lecturer-register'),
    path('lecturer/<int:lecturer_pk>/delete/', lecturer_delete, name='lecturer-delete'),
    path('student/', include('django.contrib.auth.urls')),
    path('student/register/', StudentRegister.as_view(), name='student-register'),
]

competition/models.py
from django.db import models


class Competition(models.Model):
    name = models.CharField(max_length=100)
    creation_date = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField(null=True)
    is_active = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)

    def __str__(self):
        if self.start_time is None:
            return '{} {}'.format(self.name, "No-Start-Time")
        else:
            return '{} {}'.format(self.name, self.start_time)

question/models.py
from django.db import models
from django.urls import reverse
from competition.models import Competition
import os


# determine the upload_directory for uploaded question file (including answer) in MEDIA_ROOT
def upload_directory(instance, filename):
    path = os.path.join(str(instance.question.competition.id), str(instance.question.id))
    path = os.path.join(path, filename)
    return path


class Question(models.Model):
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('question:question-details', kwargs={'question_pk': self.pk})

    def __str__(self):
        return '{} {} {}'.format(str(self.pk), self.name, self.creation_date)


class QuestionFile(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    question_file = models.FileField(upload_to=upload_directory)
    answer_file = models.FileField(upload_to=upload_directory)

    def get_question_file_text(self):
        file = open(self.question_file.path, 'r')
        return file.read()

    def get_answer_file_text(self):
        file = open(self.answer_file.path, 'r')
        return file.read()

    def __str__(self):
        return '{} || {}'.format(self.question_file.name, self.answer_file.name)

competition/views.py
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Competition
from user.models import Student
from datetime import datetime
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from helper_functions.generate_competition_table import generate_competition_table


# list of competitions
class IndexView(ListView):
    template_name = 'competition/index.html'
    context_object_name = 'competition_list'

    def get_queryset(self):
        return Competition.objects.all()


# competition details (list of questions)
class DetailsView(ListView):
    template_name = 'competition/details.html'
    context_object_name = 'competition'

    def get_queryset(self):
        return Competition.objects.get(pk=self.kwargs['competition_pk'])


class GenerateResultTable(TemplateView):
    pk_url_kwargs = 'competition_pk'
    template_name = 'competition/result_table.html'

    def get_context_data(self, **kwargs):
        context = super(GenerateResultTable, self).get_context_data(**kwargs)
        context['competition_pk'] = self.kwargs['competition_pk']
        context['table'] = generate_competition_table(self.kwargs['competition_pk'])
        return context


class CompetitionCreate(CreateView):
    model = Competition
    fields = ['name']
    template_name = 'competition/competition_form.html'

    def get_success_url(self):
        competition_pk = self.object.id
        return reverse('competition:competition-details', kwargs={'competition_pk': competition_pk})


class CompetitionUpdate(UpdateView):
    model = Competition
    fields = ['name']
    template_name = 'competition/competition_form.html'
    pk_url_kwarg = 'competition_pk'
    success_url = reverse_lazy('competition:competition-index')


class CompetitionDelete(DeleteView):
    model = Competition
    pk_url_kwarg = 'competition_pk'
    success_url = reverse_lazy('competition:competition-index')


# archive / restore competition
def change_competition_archive_status(request, **kwargs):
    competition = Competition.objects.get(pk=kwargs['competition_pk'])
    competition.is_archived = 1 - competition.is_archived
    competition.save()
    return redirect('competition:competition-index')


# set competition as active and start_time to now
def start_competition(request, **kwargs):
    competition = Competition.objects.get(pk=kwargs['competition_pk'])
    competition.start_time = datetime.now()
    competition.is_active = True
    competition.save()
    return redirect('competition:competition-details', competition_pk=competition.id)


# remove all student from competition and delete all student_answer
def restart_competition(request, **kwargs):
    competition = Competition.objects.get(pk=kwargs['competition_pk'])
    for student in competition.student_set.all():
        for student_answer in student.studentanswer_set.filter(question__competition=competition):
            student_answer.delete()
        student.competition.remove(competition)
    competition.start_time = None
    competition.is_active = False
    competition.save()
    return redirect('competition:competition-details', competition_pk=competition.id)


# set competition as inactive
def stop_competition(request, **kwargs):
    competition = Competition.objects.get(pk=kwargs['competition_pk'])
    competition.is_active = False
    competition.save()
    return redirect('competition:competition-details', competition_pk=competition.id)


# add student to competition
def join_competition(request, **kwargs):
    student = Student.objects.get(user=request.user)
    competition = Competition.objects.get(pk=kwargs['competition_pk'])
    student.competition.add(competition)
    return redirect('competition:competition-details', competition_pk=competition.id)


# remove student from competition but doesn't remove their student_answer
def remove_student_from_competition(request, **kwargs):
    if request.method == 'POST':
        student = Student.objects.get(pk=request.POST['student_id'])
        competition = Competition.objects.get(pk=kwargs['competition_pk'])
        student.competition.remove(competition)
        return redirect('competition:competition-generate-result', competition_pk=competition.id)


# function called by ajax to generate table
def generate_result_table_ajax(request, **kwargs):
    table = generate_competition_table(kwargs['competition_pk'])
    return render(request, 'competition/result_table_ajax.html', {'table': table})

templates/competition/competition_form.html
<form action="" method="post" enctype="multipart/form-data" role="form">
    {% csrf_token %}
    <legend>Add Competition</legend>

    {% include 'competition/../generic/form-template.html' %}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/competition/details.html
{% extends 'generic/base.html' %}
{% load auth_extras %}
{% comment %} template to show list of questions in a competition {% endcomment %}
{% block body %}
    <label><a href="{% url 'competition:competition-generate-result' competition.id %}">View Competition Result</a></label><br>
    {% if user.is_authenticated %}
        {% comment %} lecturer can start / restart / stop competition and add question{% endcomment %}
        {% if user|has_group:"Lecturer" %}
            {% if competition.is_active == False %}
            <label><a href="{% url 'competition:competition-start' competition.id %}">Start Competition</a></label>
            {% else %}
            <label>Competition Started! {{ competition.start_time|date:"j/n/Y h:i A" }}</label>
            <label><a href="{% url 'competition:competition-restart' competition.id %}">Restart Competition</a></label>
            <label><a href="{% url 'competition:competition-stop' competition.id %}">Stop Competition</a></label>
            {% endif %}
            <br>
            {% if competition.is_active == False %}
            <form action="{% url 'competition:question:question-add' competition.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <label>Add Question: </label>
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </form>
            {% endif %}
        {% elif user|has_group:"Student" %}
            {% if competition.is_active == True %}
            <label>Competition Started! {{ competition.start_time|date:"j/n/Y h:i A" }}</label>
            {% endif %}
        {% endif %}
    {% endif %}
    {% comment %} for each question, add a link to details page. lecturer can update / delete question {% endcomment %}
    {% if competition.question_set %}
        <h2>Question List:</h2>
        <ol>
            {% for question in competition.question_set.all %}
                <li><a href="{% url 'competition:question:question-details' competition.id question.id %}">{{ question.name }}</a>
                {% if user.is_authenticated %}
                    {% if user|has_group:"Lecturer" %}
                        {% if question.competition.is_active == False %}
                        <form action="{% url 'competition:question:question-update' competition.id question.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-edit"></span>
                            </button>
                        </form>
                        <form action="{% url 'competition:question:question-delete' competition.id question.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="question_id" value="{{ question.id }}"/>
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        {% endif %}
                    {% endif %}
                {% endif %}
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <h2>You don't have any Question</h2>
    {% endif %}
{% endblock %}

templates/competition/index.html
{% extends 'generic/base.html' %}
{% load auth_extras %}
{% comment %} template to show list of competition {% endcomment %}
{% block body %}
    {% comment %} lecturer can add competition {% endcomment %}
    {% if user.is_authenticated %}
        {% if user|has_group:"Lecturer" %}
        <form action="{% url 'competition:competition-add' %}" method="get" style="display: inline;">
            {% csrf_token %}
            <label>Add Competition: </label>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </form>
        {% endif %}
    {% endif %}
    {% if competition_list and user.is_superuser == False %}
        <h2>Competition List:</h2>
        <ul>
            {% comment %} allow lecturer to update / delete / archive competition {% endcomment %}
            {% for competition in competition_list reversed %}
                {% if user.is_authenticated %}
                    {% if user|has_group:"Lecturer" %}
                    <li>
                        {% comment %} archived competition is greyed out {% endcomment %}
                        {% if competition.is_archived %}
                        <label style="background-color: grey">#{{ competition.id }}
                        <a href="{% url 'competition:competition-details' competition.id %}">{{ competition.name }}</a></label>
                        {% else %}
                        <label>#{{ competition.id }}
                        <a href="{% url 'competition:competition-details' competition.id %}">{{ competition.name }}</a></label>
                        {% endif %}
                        {% if competition.is_active == False %}
                        <form action="{% url 'competition:competition-update' competition.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-edit"></span>
                            </button>
                        </form>
                        <form action="{% url 'competition:competition-delete' competition.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        {% endif %}
                        {% comment %} only allow archiving if competition is not in progress {% endcomment %}
                        {% if competition.is_active == False %}
                            {% if competition.is_archived == False %}
                            <a href="{% url 'competition:competition-change-archive-status' competition.id %}">Archive Competition</a></label>
                            {% else %}
                            <a href="{% url 'competition:competition-change-archive-status' competition.id %}">Restore Competition</a></label>
                            {% endif %}
                        {% else %}
                            <label>Ongoing competition!</label>
                        {% endif %}
                    </li>
                    {% endif %}
                    {% comment %} student can only join unarchived competition {% endcomment %}
                    {% if user|has_group:"Student" %}
                        {% if competition.is_archived == False %}
                        <li>
                            {% if competition not in user.student.competition.all %}
                                <label>#{{ competition.id }} {{ competition.name }}
                                <a href="{% url 'competition:competition-join' competition.id %}">Join Competition!</a></label>
                            {% else %}
                                <label>#{{ competition.id }}
                                <a href="{% url 'competition:competition-details' competition.id %}"> {{ competition.name }}</a> Joined competition!</label>
                            {% endif %}
                        </li>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        {% if user|has_group:"Lecturer" %}
        <h2>You don't have any Competition added yet</h2>
        {% endif %}
    {% endif %}
{% endblock %}

templates/competition/result_table.html
{% extends 'generic/base.html' %}
{% load staticfiles %}
{% comment %} template to display competition result table with ranking {% endcomment %}
{% block additional_header %}
    <style>
        table {
            width: 100%;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            text-align: center;
        }
        td:nth-child(2) {
            text-align: left;
        }
    </style>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
{% endblock %}

{% block question_home %} <a href="{% url 'competition:competition-details' competition_pk %}">Question List</a><br> {% endblock %}

{% block body %}
    <div id="result_table">
    </div>

    <script>
        {% comment %} run function once on load, then set to run every 5 second (1000ms * 5) {% endcomment %}
        getResultTable();
        setInterval(getResultTable, 1000 * 5);

        {% comment %} ajax script to call function to retrieve new result table {% endcomment %}
        function getResultTable(){
            $.ajax({
                url: '{% url 'competition:competition-generate-result-ajax' competition_pk %}',
                data:{
                  competition_pk: {{ competition_pk }},
                },
                success: function(data) {
                    $('#result_table').html(data);
                },
            })
        }
    </script>
{% endblock %}

templates/competition/result_table_ajax.html
{% load auth_extras %}
{% comment %} template to format the actual table {% endcomment %}
<table>
    {% for row in table %}
    <tr>
        {% if forloop.counter0 == 0 %}
            {% for column in row %}
                <th>{{ column }}</th>
            {% endfor %}
        {% else %}
            {% for column in row %}
                {% comment %} add delete option for lecturer {% endcomment %}
                {% if user.is_authenticated %}
                    {% if user|has_group:"Lecturer" %}
                        {% if forloop.counter0 == 1 and column != '--' %}
                            <td><form action="{% url 'competition:competition-remove-student' competition_pk|default:request.GET.competition_pk %}" method="post" style="display: inline; align-content: left">
                                {% csrf_token %}
                                <input type="hidden" name="student_id" value="{{ column }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        {% elif forloop.counter0 == 2 and column != '--' %}
                        {{ column }}</td>
                        {% else %}
                        <td>{{ column }}</td>
                        {% endif %}
                    {% else %}
                        {% if forloop.counter0 != 1 %}
                        <td>{{ column }}</td>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </tr>
    {% endfor %}
</table>