Results_Aggregator/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('competition/', include('competition.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^.*$', RedirectView.as_view(url='/'), name='homepage-redirect'),
]

user/urls.py
from django.urls import include, path
from .views import *

app_name = 'user'

urlpatterns = [
    # user/
    path('lecturer/', include('django.contrib.auth.urls')),
    path('lecturer/list/', LecturerList.as_view(), name='lecturer-list'),
    path('lecturer/register/', LecturerRegister.as_view(), name='lecturer-register'),
    path('lecturer/<int:lecturer_pk>/delete/', lecturer_delete, name='lecturer-delete'),
    path('student/', include('django.contrib.auth.urls')),
    path('student/register/', StudentRegister.as_view(), name='student-register'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from competition.models import Competition
from django.db.models.signals import post_save
from django.dispatch import receiver


# contains additional info for User registered in student group
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    competition = models.ManyToManyField(Competition)

    def __str__(self):
        return '{} {}'.format(self.user.username, self.competition.all())


# whenever user in student group is updated, update its student model as well
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if instance.groups.filter(name='Student').exists():
        instance.student.save()

user/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse
from .models import Student


# list of lecturer
class LecturerList(ListView):
    template_name = 'user/lecturer_list.html'
    context_object_name = 'lecturer_list'

    def get_queryset(self):
        return User.objects.all().filter(groups__name='Lecturer', is_active=True).exclude(pk=1)


# add new lecturer, create Lecturer group if it doesn't exist
class LecturerRegister(CreateView):
    form_class = UserCreationForm
    template_name = 'user/lecturer_register.html'

    def get_success_url(self):
        try:
            group = Group.objects.get(name='Lecturer')
        except Group.DoesNotExist:
            new_group = Group.objects.create(name='Lecturer')
            new_group.save()
            group = new_group
        group.user_set.add(self.object)
        return reverse('user:lecturer-list')


def lecturer_delete(request, **kwargs):
    if request.method == 'POST':
        lecturer = User.objects.get(pk=kwargs['lecturer_pk'])
        lecturer.is_active = False
        lecturer.save()
        return redirect('user:lecturer-list')


# add new student, create Student group if it doesn't exist
class StudentRegister(CreateView):
    form_class = UserCreationForm
    template_name = 'user/student_register.html'

    def get_success_url(self):
        user = self.object
        Student.objects.create(user=user)
        try:
            group = Group.objects.get(name='Student')
        except Group.DoesNotExist:
            new_group = Group.objects.create(name='Student')
            new_group.save()
            group = new_group
        group.user_set.add(user)

        # login new student user
        login(self.request, user)
        return reverse('competition:competition-index')


def student_delete(request, **kwargs):
    if request.method == 'POST':
        student = Student.objects.get(pk=request.POST['student_id'])
        student.user.is_active = False
        student.competition.remove(student)
        student.save()
        return redirect('competition:competition-generate-result')

templates/user/lecturer_list.html
{% extends 'generic/base.html' %}
{% comment %} template to list lecturer and allow add / delete {% endcomment %}
{% block body %}
    <form action="{% url 'user:lecturer-register' %}" method="get" style="display: inline;">
        {% csrf_token %}
        <label>Add Lecturer: </label>
        <button type="submit" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
    </form>

    <h2>Lecturer List:</h2>
    {% if lecturer_list %}
        <ol>
            {% for lecturer in lecturer_list %}
                <li>{{ lecturer.username }}
                <form action="{% url 'user:lecturer-delete' lecturer.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="lecturer_id" value="{{ lecturer.id }}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                </li>
            {% endfor %}
        </ol>
    {% endif %}
{% endblock %}

templates/user/lecturer_register.html
{% comment %} form to add new lecturer {% endcomment %}

<h2>Add new lecturer</h2>

{% if form.errors %}
    {% for field, error in form.errors.items %}
        <div class="alert alert-danger">
            {{ field }} - {{ error }}
        </div>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
     <div>
         <table>
             <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
             </tr>
             <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1 }}</td>
             </tr>
             <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2 }}</td>
             </tr>
         </table>
    </div>
    <button type="submit">Add</button>
</form>

templates/user/student_register.html
{% comment %} form to add new student {% endcomment %}

<h2>Register Student Account</h2>

{% if form.errors %}
    {% for field, error in form.errors.items %}
        <div class="alert alert-danger">
            {{ field }} - {{ error }}
        </div>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
     <div>
         <table>
             <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
             </tr>
             <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1 }}</td>
             </tr>
             <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2 }}</td>
             </tr>
         </table>
    </div>
    <button type="submit">Add</button>
</form>